# Generated by Django 2.2.4 on 2020-12-09 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books_Authors_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='notes',
            field=models.TextField(default='add'),
            preserve_default=False,
        ),
    ]
